// backend/server.js
import express from "express";
import cors from "cors";
import bodyParser from "body-parser";

// Node 18+ a déjà fetch globalement
// sinon: npm install node-fetch et import fetch from "node-fetch";

const app = express();
const PORT = 4000;

// Middlewares
app.use(cors());
app.use(bodyParser.json({ limit: "20mb" }));

// Petit ping de test
app.get("/", (req, res) => {
  res.send("VoxelSmith backend is running");
});

// Route principale appelée par ton frontend
app.post("/paintTexture", async (req, res) => {
  try {
    const { prompt, templatePngBase64, colorMap } = req.body;

    console.log("paintTexture called with prompt:", prompt);
    console.log(
      "colorMap keys:",
      Object.keys(colorMap || {}).slice(0, 10),
      "..."
    );

    // 1) Prépare le prompt pour Stable Diffusion
    const sdPrompt = `
Pixel-art Minecraft skin texture.
Fantasy dwarf warrior in dark iron armor, rune-engraved beard, glowing blue eyes.
Keep the layout of the colored UV islands exactly as-is.
Do NOT move or merge islands. Paint details only inside each island.
Sharp pixel blocks, no blur, no gradients.
`;

    const negativePrompt = `
photorealistic, smooth shading, blurry, low-res, text, logos, watermarks, cluttered background
`;


    // 2) Appel à Stable Diffusion WebUI (Automatic1111) en img2img
    const sdUrl = "http://127.0.0.1:7860/sdapi/v1/img2img";

    const payload = {
      init_images: [templatePngBase64], // base64 SANS prefix data:image...
      prompt: sdPrompt,
      negative_prompt: negativePrompt,

      // Réglages de génération
      width: 512,         // adapte si ton template est plus grand
      height: 512,
      denoising_strength: 0.35, // faible pour respecter le layout
      steps: 25,
      cfg_scale: 7,
      sampler_name: "Euler a",

      // Garder la mise à l’échelle simple
      resize_mode: 0, // Just resize
    };

    const sdResponse = await fetch(sdUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!sdResponse.ok) {
      const txt = await sdResponse.text();
      console.error("Stable Diffusion API error:", txt);
      return res.status(500).send("Stable Diffusion API error");
    }

    const sdData = await sdResponse.json();

    if (!sdData.images || !sdData.images[0]) {
      console.error("No images in Stable Diffusion response");
      return res.status(500).send("No image generated by Stable Diffusion");
    }

    const imageBase64 = sdData.images[0]; // déjà base64 PNG par défaut

    // 3) Renvoie au frontend
    return res.json({ imageBase64 });
  } catch (err) {
    console.error("paintTexture backend error:", err);
    return res.status(500).send("paintTexture backend error");
  }
});

// Lancer le serveur
app.listen(PORT, () => {
  console.log(`Backend server listening on http://localhost:${PORT}`);
});
